# Main Server Configuration
[server]
name = "main"
host = "0.0.0.0"
port = 8086
enabled = true
upstreams = ["backend1", "backend2", "backend3"]

# Load Balancer Configuration
[load_balancer]
method = "weighted_round_robin"
timeout = "30s"
retry_attempts = 3

# Logging Configuration
[logging]
level = "info"
file = "logs/surikiti_main.log"

# Proxy Configuration
[proxy]
max_body_size = 10485760  # 10MB in bytes
request_timeout = "30s"
response_timeout = "30s"
keep_alive_timeout = "60s"
max_idle_conns = 100
max_idle_conns_per_host = 10
max_conns_per_host = 50
enable_compression = true
enable_websocket = false
websocket_timeout = "60s"
websocket_buffer_size = 4096

# CORS Configuration
[cors]
enabled = true
allowed_origins = ["http://localhost:3000"]
allowed_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
allowed_headers = ["Content-Type", "Authorization", "X-Requested-With"]
allow_credentials = true
max_age = 3600