# WebSocket Server Configuration
[server]
name = "websocket_only"
host = "0.0.0.0"
port = 9087
websocket_port = 9088
enabled = false
upstreams = ["ws_backend1"]

# Load Balancer Configuration
[load_balancer]
method = "round_robin"
timeout = "45s"
retry_attempts = 5

# Logging Configuration
[logging]
level = "warn"
file = "logs/surikiti_websocket.log"

# Proxy Configuration
[proxy]
max_body_size = 20971520  # 20MB in bytes
request_timeout = "45s"
response_timeout = "45s"
keep_alive_timeout = "120s"
max_idle_conns = 200
max_idle_conns_per_host = 20
max_conns_per_host = 100
enable_compression = true
enable_websocket = true
websocket_timeout = "120s"
websocket_buffer_size = 8192

# CORS Configuration
[cors]
enabled = true
allowed_origins = ["*"]
allowed_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"]
allowed_headers = ["*"]
allow_credentials = false
max_age = 7200